### PR TITLE
fix packet header and base64 alphabet

### PR DESCRIPTION
**Pull request by sevenEng**
per https://github.com/nojb/ocaml-macaroons/issues/5

### CODE REVIEW

**Comment by nojb** [comment]
Looks good, merging.

**Comment by nojb** [comment]
Thanks !

**Comment by sevenEng** [comment]
Hi @nojb :smile: 
I know you haven't work actively on this for long, but just check if there will be a plan of new release to include this, we are currently using a fork and a git pin to have this. With a probable new release, it would bring us much convenience when managing some repos. Thanks!

**Comment by nojb** [comment]
Thanks for the ping @sevenEng!  This had gotten lost among in the queue.  I will make a new release tonight.

**Comment by sevenEng** [comment]
Cool! Many thanks! :+1:

**Comment by nojb** [comment]
Done in https://github.com/ocaml/opam-repository/pull/9786.

**Pull request merged**
